Матрица представляет собой набор чисел, расположенных по строкам и столбцам, как в таблице.

In [ ]:
Матрицу можно создать командой .matrix или .array. За размер матрицы отвечает команда shape. 

In [2]:
import numpy as np
import pandas as pd
A = np.array([[-1, 5,3], [2,2,1], [0,3,1], [2,4,12]])
B = np.matrix([[-1, 5,3], [2,2,1], [0,3,1], [2,4,12]])

In [6]:
A.shape

(4, 3)

Матрицы складываются и вычитаются поэлементно. Складывать и вычитать можно только матрицы одинакового размера.

Умножение матрицы на скаляр снова аналогично векторной операции. Числовые множители также можно выносить из матрицы.

Операторы для сложения матриц и умножения их на числа в Python аналогичны векторным

При транспонировании строки матрицы записываются в столбцы и матрица переворачивается. Частный случай: транспонирование векторов. Если транспонировать вектор-столбец, получится вектор-строка и наоборот. Для операции транспонирования в питоне есть команда, которая обозначается Т. Заметим, что Python не умеет транспонировать одномерные массивы.

Симметричная матрица транспонируется в саму себя.

In [4]:
A = np.matrix([[-1, 5,3], [2,2,1], [0,3,1], [2,4,12]])

In [5]:
A

matrix([[-1,  5,  3],
        [ 2,  2,  1],
        [ 0,  3,  1],
        [ 2,  4, 12]])

In [6]:
A.T

matrix([[-1,  2,  0,  2],
        [ 5,  2,  3,  4],
        [ 3,  1,  1, 12]])

In [7]:
v = np.array([7,5,-1])
v

array([ 7,  5, -1])

In [8]:
v.T

array([ 7,  5, -1])

In [9]:
# как двумерный массив Numpy
np.array( [ [1,1] , [2,3] , [4,5] ] )

array([[1, 1],
       [2, 3],
       [4, 5]])

In [10]:
data=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
df = pd.DataFrame(data)

A = df.values

print('Data Frame:')
print(df)
print('Matrix:')
print(A)

Data Frame:
    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
# размер матрицы
print(np.shape(A))
print(A.shape)

(4, 3)
(4, 3)


In [16]:
# вектор-столбец
x = np.array([1,2,3])
np.reshape(x,(3,1))

array([[1],
       [2],
       [3]])

In [18]:
# вектор-строка
np.reshape(x,(1,3))

array([[1, 2, 3]])

In [20]:
# вектор-строка var2
x_row = np.array([1, 2, 3], ndmin=2)
print(x_row, np.shape(x_row))

[[1 2 3]] (1, 3)


In [21]:
# индексация матриц (двумерных массивов numpy)
print('матрица А:')
print(A)
print('Первая строка матрицы А:')
print(A[0])
print('Третий столбец матрицы А:')
print(A[:,2])
print('Элемент а_43:')
print(A[3,2])

матрица А:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Первая строка матрицы А:
[1 2 3]
Третий столбец матрицы А:
[ 3  6  9 12]
Элемент а_43:
12


In [22]:
# нулевая
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# матрица единиц
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
# единичная
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# Диагональная
diagonal = [1,2,3] # какие элементы будут лежать на диагонали
np.diag(diagonal)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [27]:
# Шаровая
5*np.eye(3)

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [28]:
A = np.array([[1,1],[2,3],[4,5]])
B = np.array([[1,-1],[-2,3],[4,-5]])

In [29]:
A

array([[1, 1],
       [2, 3],
       [4, 5]])

In [30]:
B

array([[ 1, -1],
       [-2,  3],
       [ 4, -5]])

In [31]:
A+B

array([[2, 0],
       [0, 6],
       [8, 0]])

In [32]:
B+A

array([[2, 0],
       [0, 6],
       [8, 0]])

In [33]:
A-B

array([[ 0,  2],
       [ 4,  0],
       [ 0, 10]])

In [34]:
2*A

array([[ 2,  2],
       [ 4,  6],
       [ 8, 10]])

In [35]:
A.T

array([[1, 2, 4],
       [1, 3, 5]])

In [36]:
# как транспонировать вектор?
x=np.array([1,2,3])
x.T # такой вариант не транспонирует вектор, только матрицу

array([1, 2, 3])

In [37]:
x_col = np.reshape(x,(3,1))
print(x_col)
print(np.shape(x_col))# а такой транспонирует

[[1]
 [2]
 [3]]
(3, 1)


In [38]:
x_col.T # а из столбца в строку транспонирует

array([[1, 2, 3]])

In [39]:
print(np.shape(x))
print(np.shape(x_col))
print(np.shape(x_col.T))

(3,)
(3, 1)
(1, 3)


In [40]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

In [44]:
Inc = np.matrix([Husband_Income, Wife_Income, Mother_In_Law_Income]).T
Inc

matrix([[100, 150,  90],
        [220, 200,  80],
        [140, 130, 100]])

In [45]:
Cons = np.matrix([Husband_Сonsumption, Wife_Сonsumption, Mother_In_Law_Сonsumption]).T
Cons

matrix([[ 50, 100, 100],
        [ 50,  80,  20],
        [ 60, 140, 140]])

In [48]:
Inc = 0.87*Inc
Inc

matrix([[ 87. , 130.5,  78.3],
        [191.4, 174. ,  69.6],
        [121.8, 113.1,  87. ]])

In [49]:
P = Inc - Cons
P

matrix([[ 37. ,  30.5, -21.7],
        [141.4,  94. ,  49.6],
        [ 61.8, -26.9, -53. ]])

Операция умножения двух матриц возможна только в том случае, если число столбцов в первой матрице равно числу строк во второй. Если матрица A содержит m строк, а матрица B содержит n столбцов, то результатом их умножения будет матрица С размера  m × n. Умножение матриц некоммутативно, то есть  AB ≠ BA.

В Python матрицы можно умножить командой np.dot. При перемене мест сомножителей результат также меняется.

In [50]:
A = np.array([[-1, 5], [2,2], [0,3]])
B = np.matrix([[-1, 5,3], [2,2,1]])

In [51]:
A

array([[-1,  5],
       [ 2,  2],
       [ 0,  3]])

In [52]:
B

matrix([[-1,  5,  3],
        [ 2,  2,  1]])

In [53]:
np.dot(A, B)

matrix([[11,  5,  2],
        [ 2, 14,  8],
        [ 6,  6,  3]])

In [54]:
np.dot(B, A)

matrix([[11, 14],
        [ 2, 17]])

 Умножать матрицу на вектор-столбец можно только справа. Умножать вектор-строку на матрицу можно только слева.

Тензорное произведение а на b = произведение а на b.T, т.е умножаем вектор столбец на вектор строку: стбц [1,2] * стбц [3,4].T = [[3,4], [6,8]]

 Нулевая матрица играет роль нуля не только в сложении, но в умножении матриц (независимо от порядка).

Единичная матрица (np.eye(n)) играет роль единицы: при умножении на неё ничего не меняется. При умножении на шаровую матрицу каждый элемент матрицы А умножился на 2, что равносильно умножению матрицы А на число 2.

Единичная и шаровая матрицы перестановочны с любой квадратной матрицей, результат не зависит от порядка умножения.

Диагональные матрицы неперестановочны с другими в общем случае. Но перестановочны между собой. Это их свойство будет активно использоваться при работе с матрицами ковариаций многомерных нормальных распределений.

Делители нуля — это специальные ненулевые элементы, которые дают ноль при умножении.Если матрицы А и В — делители нуля, то строки левого сомножителя ортогональны столбцам правого. (скалярное произведение равно 0)

При транспонировании меняется порядок произведения (A*B).T = B.T * A.T

Матрицей Грама системы векторов называется матрица, составленная из их скалярных произведений. матрица Грама системы векторов всегда имеет вещественные собственные числа и диагонализируется, а если векторы линейно независимы, то ещё и обратима. Этим мы будем пользоваться при построении и апгрейдах модели линейной регрессии.

Матрицы Х и Х.Т можно умножать в любом порядке. В обоих случаях получится симметричная квадратная матрица.

In [55]:
# произведение матриц, тип array
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [56]:
A

array([[ 7,  7,  8],
       [ 6, 11,  8],
       [ 8,  7,  7]])

In [57]:
B

array([[-2, -2,  2],
       [ 3,  1,  3],
       [ 1,  0,  0]])

In [58]:
# Т.к тип array, то * - это поэлементное умножение
A*B

array([[-14, -14,  16],
       [ 18,  11,  24],
       [  8,   0,   0]])

In [60]:
# Матричное умножение
np.dot(A,B)

array([[15, -7, 35],
       [29, -1, 45],
       [12, -9, 37]])

In [61]:
# Матричное умножение
A@B

array([[15, -7, 35],
       [29, -1, 45],
       [12, -9, 37]])

In [67]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[25 60]
 [23 55]
 [24 78]]


In [62]:
# Порядок умножения AB != BA
B@A

array([[-10, -22, -18],
       [ 51,  53,  53],
       [  7,   7,   8]])

In [63]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 6 11  9  5  9]
 [ 5  8  5  5 10]
 [11 10 10  7  7]]
B:
 [[0 3]
 [1 0]
 [0 1]
 [1 3]
 [1 2]]


In [64]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[25, 60],
       [23, 55],
       [24, 78]])

In [65]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [66]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [68]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[-1  3  2 -1]
 [-2 -1  2 -4]
 [ 2  0  0  1]
 [-3 -4  0  1]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[-1  6  0  1]
 [-2 -2  0  4]
 [ 2  0  0 -1]
 [-3 -8  0 -1]]
DA:
 [[-1  3  2 -1]
 [-4 -2  4 -8]
 [ 0  0  0  0]
 [ 3  4  0 -1]]


In [69]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [70]:
b@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [71]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [72]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [73]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [74]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [75]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

In [76]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [77]:
A@x

array([26, 30])

In [79]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

In [81]:
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [82]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [84]:
A = np.array([x,y,z])
A@A.T

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

In [96]:
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
com = [0.2, 0.2, 0.3, 0.1, 0.1]

In [86]:
Count_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

In [87]:
Price_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

In [101]:
com

[0.2, 0.2, 0.3, 0.1, 0.1]

In [97]:
Count_DF_m = np.array(Count_DF)
Price_DF_m = np.array(Price_DF)
com_m = np.array(com)

In [108]:
Price_DF_m*Count_DF_m

array([[20. ,  7.5, 12. , 12. , 10. ],
       [ 3.6, 52.5,  3. , 25. ,  6. ],
       [24. , 24. ,  0. , 15. ,  8. ],
       [ 7.2,  9.6, 50.4, 11.2, 10. ],
       [15. , 87.5, 54. , 25. , 27. ],
       [50. , 15. ,  6. , 34. , 30. ],
       [24.2,  1. ,  6. , 12.5, 34. ],
       [31.5,  0. , 77.5, 31. , 56. ]])

In [103]:
Salon_m = (Count_DF_m*Price_DF_m)@com_m
Salon_m

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [115]:
Styls_m = (Count_DF_m*Price_DF_m)@(np.ones(5)-com_m)
Styls_m

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

В числах деление — это умножение на обратное число. Обратным к числу а называется такое число a^-1, которое в произведении с a даст единицу. Обратные  есть у всех чисел, кроме нуля.Свойство: обратное число всегда одно и неважно, с какой стороны умножать на него.

Попробуем обобщить понятие обратного числа на квадратные матрицы. В роли единицы выступает единичная матрица Е. Перед нами встаёт задача научиться подбирать такую матрицу, которая даст в произведении с исходной единичную. Найти обратную матрицу в питоне - np.linalg.inv(A)

In [116]:
A = np.matrix("1,2,3; 4,5,6; 7,8,10")
A_inv = np.linalg.inv(A)
A_inv

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

In [121]:
A*A_inv

matrix([[ 1.00000000e+00, -4.44089210e-16, -1.11022302e-16],
        [ 4.44089210e-16,  1.00000000e+00, -2.22044605e-16],
        [ 4.44089210e-16,  8.88178420e-16,  1.00000000e+00]])

In [122]:
A = np.matrix("1,2; 2,4")
A_inv = np.linalg.inv(A)
A_inv

LinAlgError: Singular matrix

In [124]:
A = np.matrix("1,2; 2,5")
A_inv = np.linalg.inv(A)
A_inv

matrix([[ 5., -2.],
        [-2.,  1.]])

Определитель матрицы — это число, специальная числовая характеристика квадратных матриц, которая является своего рода мерой вырожденности матрицы и для размерности 2 × 2 вычисляется по следующему правилу det([[a,b], [c,d]]) = ad-bc. В Python определитель считается командой linalg.det из библиотеки numpy

Определитель единичной матрицы = 1, определитель диагональной матрицы - произведение диагональных элементов. Определитель А.Т = определителю А. Определитель проиведения матриц, равен произведению определителей матриц.

Определение: Матрицы с нулевым определителем называются вырожденными. Если определитель А = 0, то матрица А вырожденная; у матрицы А не существует обратной; столбцы и строки матрицы А линейно зависимы.

In [125]:
A = np.matrix("2,0,0; 0,1,0; 0,0,4")
np.linalg.det(A)

7.999999999999998

In [126]:
np.linalg.det(np.linalg.inv(A))

0.12500000000000003

Метод определения линейной зависимости/независимости при помощи СЛАУ:

1. Записать СЛАУ в матричном виде и решить ее.
2. Есть ненулевые решения — векторы линейно зависимы.
3. Нет ненулевых решений — векторы линейно независимы.

Определение: Ранг матрицы — количество линейно независимых столбцов.
Определение: Ранг системы векторов — размерность этой системы. 
После преобразований матрицы к ступенчатому виду ранг равен количеству ступенек.
Ранг системы векторов равен количеству линейно независимых векторов, т.е. размерности всей системы.
Чтобы исследовать систему векторов на линейную зависимость / независимость с помощью ранга, достаточно записать эти векторы в матрицу по столбцам и найти ранг полученной матрицы. Ранг будет равен количеству линейно независимых векторов в системе.

Определение: Базис — максимальная линейно независимая подсистема векторов.
В системе векторов можно выбрать ровно столько линейно независимых векторов, какой у нее ранг.
Определение: Базис матрицы — максимальная линейно независимая подсистема столбцов матрицы.
Базисов может быть несколько.

Для вычисления ранга матриц в библиотеке nupmy есть команда linalg.matrix_rank

Свойства ранга
Если  А — прямоугольная матрица размера m × k, то rk(A) ≤ min(m, k).
Если rk(A) = min(m, k), то А —матрица максимального ранга.
Квадратная матрица А размера n × n обратима, если:
det(A) ≠ 0
столбцы (или строки) матрицы А линейно независимы 
rk(A) = n
Квадратная матрица А размера n × n вырождена, если:
rk(A) < n
Чем меньше rk(A), тем более вырождена A
Для успешного построения регрессий необходимо научиться избавляться от линейной зависимости.

In [128]:
A = np.matrix("1,0,3,5; 0,4,5,5; 0,0,0,0; 0,0,0,0")
B = np.matrix("1,0,3,5; 0,4,5,5; 0,0,0,4; 0,0,0,0")

In [129]:
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(B))

2
3


In [130]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

In [131]:
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [132]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [135]:
B = np.array([v1,v2,v3,v4])
np.linalg.matrix_rank(B)

4

In [138]:
C = B@B.T

In [139]:
np.linalg.det(C)

3716647.9999999995

In [140]:
np.linalg.matrix_rank(C)

4

In [141]:
np.linalg.inv(C)

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])