1. Вектор — это набор чисел, записанных в определённом порядке (в столбик или в строчку). s
2. Координаты вектора — это числа, из которых он состоит. 
3. Размерность вектора — это количество координат.dim(s)

In [22]:
import numpy as np
import pandas as pd
s = np.array([33,65,50,45]) # вектор - одномерный массив 
print('Третья координата', s[2])
print('Размерность вектора', len(s))

Третья координата 50
Размерность вектора 4


In [3]:
apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])

Эта последовательность чисел и называется вектором. Вектор характеризует конкретный объект — конкретную квартиру. А число в той или иной позиции вектора описывает конкретный признак объекта. То есть вектор — это, по сути, одномерный массив: 

In [4]:
# В NumPy вектор и массив - одно и то же. 
# Исключение - понятие вектор-столбец и вектор-строка - фактически двумерные массивы, 
# где один из атрибутов shape равен 1.

print("ndim:", apartment.ndim) # число осей (измерений) массива - ndim: 1
print("shape:", apartment.shape) # размеры массива, для вектора определена только длина - shape: (6, )

ndim: 1
shape: (6,)


In [5]:
# сгенерируем новый признак — отношение жилой площади к общей
share_living_space = apartment[1]/apartment[0] # вычислим долю жилой площади в квартире
apartment = np.delete(apartment, [0, 1]) # избавимся от старых признаков
apartment = np.append(apartment, share_living_space) # добавим в конец нашего массива новый признак share_living_space

In [7]:
print(round(share_living_space,2))
print(apartment.shape)

0.53
(5,)


Сложение векторов происходит поэлементно, первая координата складывается с первой, вторая со второй и так далее. Вычитаются векторы так же поэлементно. Сложение и вычитание векторов в Python происходит при помощи знаков + и -. Причём важно задать векторы именно как массивы NumPy, а не как обычные списки типа list.

In [8]:
a = np.array([10,8,5,1])
b = np.array([5,15,9,7])
print(a+b)
print(a-b)

[15 23 14  8]
[ 5 -7 -4 -6]


Умножение вектора на число также происходит поэлементно, то есть каждая координата вектора умножается на заданное число.Если коэффициент пропорциональности положительный, векторы сонаправлены, если отрицательный — противоположно направлены. Геометрически это значит, что векторы лежат на одной прямой (или параллельных прямых) и направлены в одну или противоположные стороны. В Python число умножается на массив numpy обычным оператором умножения.

In [9]:
a = np.array([120, 45, 68])
omega = 0.2
print(omega*a)

[24.   9.  13.6]


In [10]:
a = np.array([120,150,90])
b = np.array([130,130,130])
c = np.array([2,3,2.5])
d = 72
e = c*d
f = a+b+e
print(e)
print(f)

[144. 216. 180.]
[394. 496. 400.]


Линейная комбинация — это объединение двух предыдущих операций в одну: каждый вектор умножается на соответствующий ему коэффициент, все умноженные векторы складываются. Линейная комбинация — это сумма векторов, умноженных на некоторые числа. В Python линейная комбинация полностью соответствует своему названию и вычисляется как комбинация сложения векторов и умножения  вектора на число. 

In [11]:
p = np.array([2,4,5])
v = np.array([8,10,2])
s = np.array([0,12,7])
500*p+100*v+0*s

array([1800, 3000, 2700])

Из заданного набора векторов можно получить нулевую линейную комбинацию, умножив каждый вектор на ноль. Такие комбинации называются тривиальными. Линейная комбинация называется тривиальной, если все коэффициенты равны нулю.Линейная комбинация называется нетривиальной, если хотя бы один из коэффициентов не равен нулю.

Векторы называются линейно зависимыми, если существует нулевая нетривиальная комбинация этих векторов. При этом один из линейно зависимых векторов, но не обязательно любой, можно выразить через другие, то есть представить как их линейную комбинацию.

Векторы называются линейно независимыми, если не существует нулевой нетривиальной комбинации этих векторов.При этом ни один вектор не выражается через другие векторы.

In [12]:
x = np.array([4,5])
y = np.array([2,1])
u = np.array([1,0])
2*x+(-3)*y+5*u

array([7, 7])

In [13]:
s = np.array([3,4,5,9])
p = np.array([1,5,3,6])
a = 200
b = 400

p*b - a*s

array([-200, 1200,  200,  600])

Всего есть четыре основных способа умножить векторы:

1. Скалярное произведение. Результат — число. 
2. Векторное произведение. Результат — вектор.
3. Смешанное произведение. Результат — число. 
4. Тензорное произведение. Результат — матрица.

Чтобы найти скалярное произведение двух векторов, необходимо перемножить их координаты с одинаковыми номерами и сложить то, что получится. (a,b) В Python скалярное произведение векторов вычисляется при помощи команды np.dot или оператора @.

In [17]:
a = np.array([65,70,120,30])
w = np.array([0.4,0.4,0.2,0.8])
np.dot(a,w)

102.0

In [18]:
s = a@w
s

102.0

Длина вектора вычисляется как квадратный корень из скалярного произведения вектора с самим собой. Для нас это это просто корень из суммы квадратов координат, как в теореме Пифагора — для случая с размерностью вектора равной двум (геометрически это длина отрезка). Длина вектора всегда неотрицательна и показывает, как близок вектор к нулевому.

In [19]:
l = np.linalg.norm(a)
l

156.28499608087785

Нормирование вектора — это получение вектора с тем же направлением, что и исходный, но нормой 1. Нормировка - вектор имеющий то же направление, но длина его = 1. Надо поделить вектор на его длину. Норма вектора (знаменатель) вычисляется как корень из суммы квадратов его компонент. Её физический смысл: норма показывает, насколько вектор «большой». Длина вектора (в физическом смысле) — это то же, что и норма, применимо к векторам в реальном пространстве.

In [20]:
a/np.linalg.norm(a)

array([0.41590685, 0.44789968, 0.76782803, 0.19195701])

Векторы  и  называются ортогональными, если их скалярное произведение равно нулю.

In [15]:
a = np.array([4,5,-1])
w = np.array([2,0,1])
np.dot(a,w)

7

In [23]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent' :[65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area' :[50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

In [25]:
Hut_Paradise_Arr = Hut_Paradise_DF.values

In [27]:
Hut_Paradise_Arr[4]

array([40, 33,  1,  6, 20, 16])

In [28]:
Hut_Paradise_Arr[:,3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5])

In [30]:
Hut_Paradise_Arr[2,3] # на каком этаже расположена квартира номер 3 (индекс 2)

10

In [32]:
Hut_Paradise_Arr.shape[0]

9

In [37]:
all_area = Hut_Paradise_Arr[:,1] 
liv_area = Hut_Paradise_Arr[:,5]
not_liv_area = all_area - liv_area # вектор нежилой площади
not_liv_area

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

In [39]:
Hut_Paradise_Arr[:,0]*0.4

array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

In [40]:
demo_lenght = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])

np.dot(demo_lenght, Hut_Paradise_Arr[:,4])

In [42]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [43]:
2*v+(-3)*w

array([-3, 14,  3,  4,  2])

In [44]:
u/np.linalg.norm(u)

array([0.8660254 , 0.        , 0.28867513, 0.28867513, 0.28867513])

In [45]:
v/np.linalg.norm(v)

array([ 0.        ,  0.33333333,  0.        ,  0.66666667, -0.66666667])

In [46]:
w/np.linalg.norm(w)

array([ 0.21320072, -0.85280287, -0.21320072,  0.        , -0.42640143])