In [1]:
import numpy as np
import pandas as pd

In [2]:
arr1 = np.array([1,2,3,4])

In [3]:
arr1.dtype

dtype('int64')

In [4]:
arr1

array([1, 2, 3, 4])

In [5]:
arr2 = np.array([5,6,7,8], dtype = float)
arr2.dtype

dtype('float64')

In [6]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.shape(arr3)

(3, 3)

In [8]:
# DataFrame -> в массив numpy
df = pd.DataFrame()
x = df.values
type(x)

numpy.ndarray

In [9]:
# Series -> в массив numpy
my_series = pd.Series([5, 6, 7, 8, 9, 10])
y = my_series.values
y

array([ 5,  6,  7,  8,  9, 10])

In [10]:
# одномерный массив из пяти элементов, память для которого выделена, но не инициализирована
np.empty(5) 

array([0., 0., 0., 0., 0.])

In [11]:
# массив размером 10x7, заполненный нулями 
np.zeros((10, 7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [12]:
# массив размером 3х3х3, заполненный единицами 
np.ones((3,3,3)) 

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [13]:
# единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3
np.eye(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# массив 3x5 заполненный числом 3.14
np.full((3, 5), 3.14) 

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
# одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7
np.arange(0, 21, 7) 

array([ 0,  7, 14])

In [16]:
# массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
# массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)
np.random.randint(0, 10, (3, 3))  

array([[7, 9, 5],
       [1, 7, 4],
       [7, 8, 0]])

In [18]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [19]:
np.full((5,5), 1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
np.array([[1,2,3,4,5], [5,1,2,3,4], [4,5,1,2,3], [3,4,5,1,2], [2,3,4,5,1]])

array([[1, 2, 3, 4, 5],
       [5, 1, 2, 3, 4],
       [4, 5, 1, 2, 3],
       [3, 4, 5, 1, 2],
       [2, 3, 4, 5, 1]])

In [21]:
np.array([i for i in range(11) if i%2])

array([1, 3, 5, 7, 9])

In [22]:
my_array = np.array([x for x in range(10)])
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
my_array[5]

5

In [24]:
my_array[-1]

9

In [25]:
my_array[3:6]

array([3, 4, 5])

In [26]:
my_array[1:8:3]

array([1, 4, 7])

In [27]:
my_array2 = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
my_array2

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [45, 46, 47, 48]])

In [28]:
my_array2[1][2]

12

In [29]:
my_array2[1,2]

12

In [30]:
my_array2[1]

array([10, 11, 12, 13])

In [31]:
my_array2[0:3, 2]# 'элементы 0-2 из 2 столбца'

array([ 3, 12, 47])

In [33]:
my_array2[1:3, 2:]

array([[12, 13],
       [47, 48]])

In [34]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [46]:
list1 = big_secret[0:, -1].tolist()
list_len = 0
for x in range(0, len(list1)):
    list_len += list1[x]
print(list_len)

3154.332495807108


In [52]:
big_secret2 = big_secret[0:5, 0:5]
diag_elems = 0
for x in range(0, len(big_secret2[0])):
    diag_elems += big_secret2[x,x]
print(diag_elems)

121.37188663699624


In [63]:
big_secret3 = big_secret[0:5, -5:]
diag_elems2 = 1
for x in range(0, len(big_secret3[0])):
    diag_elems2 *= big_secret3[x,x]
print(diag_elems2)

341505315559.2347


In [66]:
my_array = np.random.randint(1, 100, (4, 6))
my_array

array([[74, 56, 19, 91, 27, 15],
       [66, 63, 21, 53, 60, 55],
       [ 6,  4, 75, 63, 12, 70],
       [72, 94, 77, 13, 81,  8]])

In [68]:
my_slice = my_array[1:3, 2:4]
my_slice

array([[21, 53],
       [75, 63]])

In [69]:
my_slice[:] = 0
my_array

array([[74, 56, 19, 91, 27, 15],
       [66, 63,  0,  0, 60, 55],
       [ 6,  4,  0,  0, 12, 70],
       [72, 94, 77, 13, 81,  8]])

In [82]:
big_secret[0::2,0::2]=-1
big_secret[1::2, 1::2]=1

In [84]:
big_secret2 = big_secret[0:5, 0:5]
diag_elems = 0
for x in range(0, len(big_secret2[0])):
    diag_elems += big_secret2[x,x]
print(diag_elems)

-1.0


In [86]:
big_secret3 = big_secret[0:5, -5:]
diag_elems2 = 1
for x in range(0, len(big_secret3[0])):
    diag_elems2 *= big_secret3[x,x]
print(diag_elems2)

-1.0


In [87]:
big_secret3

array([[-1.00000000e+00,  2.76000000e+02, -1.00000000e+00,
         4.90000000e+02, -1.00000000e+00],
       [ 3.30454233e+01,  1.00000000e+00,  3.31058907e+01,
         1.00000000e+00,  3.31662479e+01],
       [-1.00000000e+00,  2.20900000e+03, -1.00000000e+00,
         2.40100000e+03, -1.00000000e+00],
       [ 3.30454233e+01,  1.00000000e+00,  3.31058907e+01,
         1.00000000e+00,  3.31662479e+01],
       [-1.00000000e+00,  2.76000000e+02, -1.00000000e+00,
         4.90000000e+02, -1.00000000e+00]])